name: CI with Accessibility Testing

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Get Date for cachindg
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      # Cache Buildozer Global Directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer project directory
      - name: Cache Buildozer
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Install dependencies
      - name: Install Python dependencies (Kivy, pyttsx3, ultralytics)
        run: |
          python -m pip install --upgrade pip
          pip install kivy pyttsx3 ultralytics

      # Build with Buildozer
      - name: Build Android app with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug

      # Accessibility Tests (Replace with your chosen tool)
      - name: Run Accessibility Tests with MonkeyTalk
        uses: google/android-emulator@v1
        with:
          # Configure emulator (API level, etc.)
          api-level: 28  # Adjust to your target API level
          name: accessibility-test
        env:
          MONKEYTALK_HOST: localhost  # Assuming MonkeyTalk server runs locally
        run: |
          # Grant permissions (adjust paths)
          adb -s $ANDROID_EMULATOR_HOST shell pm grant com.yourapp.objectdetection android.permission.WRITE_EXTERNAL_STORAGE
          adb -s $ANDROID_EMULATOR_HOST shell pm grant com.yourapp.objectdetection android.permission.READ_EXTERNAL_STORAGE
          adb -s $ANDROID_EMULATOR_HOST shell pm grant com.yourapp.objectdetection android.permission.RECORD_AUDIO

          # Run MonkeyTalk tests (adjust paths)
          monkeytalk run /path/to/your/monkeytalk/accessibility_tests.mt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      # Upload accessibility testing report (if applicable)
      - name: Upload Accessibility Test Report
        uses: actions/upload-artifact@v2
        if: success() && steps.run-accessibility-tests.outputs.report  # Upload only if report exists
        with:
          name: accessibility-report
          path: /path/to/accessibility_test_report.xml  # Adjust the path
